name: 'Mark stale issues and PRs'
on:
  schedule:
    - cron: '7 1 * * *'
  workflow_dispatch:
    inputs:

permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  stale:  # call reusable workflow from central '.github' repo
    uses: open-component-model/.github/.github/workflows/stale.yml@41c2401b742871f5a9c3464357c0c5a589f81843 # main
    secrets: inherit